[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 300
via_ir = false
ffi = true


# See more config options https://github.com/foundry-rs/foundry/tree/master/config